gitops-tenant:
  fullnameOverride: mlops-demo

  adminGroup:
    members:
      - opentlc-mgr
      - user1

  namespaces:
    - nameSuffix: gitops
      role: gitops
      adminGroupRole: admin
    - nameSuffix: pipelines
      role: pipelines
      adminGroupRole: admin
      annotations:
        operator.tekton.dev/prune.resources: "taskrun, pipelinerun"
        operator.tekton.dev/prune.keep-since: "7200"
    - nameSuffix: datascience
      role: dev
      adminGroupRole: admin
      createOperatorGroup: true
    - nameSuffix: dev
      role: dev
      nameOverride: ""
      adminGroupRole: admin
      createOperatorGroup: true
    - nameSuffix: test
      role: test
      nameOverride: ""
      adminGroupRole: view
      createOperatorGroup: true
    - nameSuffix: prod
      role: prod
      nameOverride: ""
      adminGroupRole: view
      createOperatorGroup: true

  additionalRoles:
    - name: sealed-secrets-deployer
      subject:
        name: argocd-argocd-application-controller
      rules:
        - verbs:
            - get
            - list
            - watch
            - create
            - update
            - patch
            - delete
          apiGroups:
            - 'bitnami.com'
          resources:
            - 'sealedsecrets'
    - name: grafana-deployer
      subject:
        name: argocd-argocd-application-controller
      rules:
        - verbs:
            - get
            - list
            - watch
            - create
            - update
            - patch
            - delete
          apiGroups:
            - 'integreatly.org'
          resources:
            - 'grafanas'

  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: cluster-monitoring-view
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-monitoring-view
  subjects:
    - kind: ServiceAccount
      name: grafana-serviceaccount
      namespace: patch-me